### PR TITLE
optimized code

### PR DESCRIPTION
**Pull request by qazer2687**

### CODE REVIEW

**Comment by qazer2687** [comment]
lgtm

**Review by devnote-dev — CHANGES_REQUESTED** [review]
Too many changes, needs rebase.

**Comment by camwhi-te** [comment]
I mean, this fixes the present bugs in one PR... LGTM!

**Comment by camwhi-te** [comment]
image
image

Impressive, I must admit

**Comment by qazer2687** [comment]
added documentation

**Review by devnote-dev — APPROVED** [review]
Looking good now

**Comment by qazer2687** [comment]
ported to python

**Comment by qazer2687** [comment]
python not efficient, ported to brainfuck

**Comment by devnote-dev** [comment]
I think we should rewrite it in Rust.

**Comment by qazer2687** [comment]
chatgpt has no idea how to write brainfuck, fixed bug

**Comment by qazer2687** [comment]
> I think we should rewrite it in Rust.

sure thing il work on it

**Comment by qazer2687** [comment]
works well 👍

**Review by devnote-dev — COMMENTED** [review]
Something is off about this... 🤔

**Comment by qazer2687** [comment]
of course, my bad

**Review by devnote-dev — APPROVED** [review]
LGTM

**Comment by qazer2687** [comment]
rust is too obscure so i ported it to a more mainstream language

**Comment by camwhi-te** [comment]
Please create a GitHub Action for linting, that code looks messy.

**Comment by GomorrhaDev** [comment]
Whitespace doesn't look that messy. You should switch to it.

**Comment by GomorrhaDev** [comment]
Because some people find such a light programming language too hard. Here is the code in whitespace:

**Comment by GomorrhaDev** [comment]
https://pastebin.pl/view/raw/d4b07407

**Comment by qazer2687** [comment]
> Whitespace doesn't look that messy. You should switch to it.

👍

**Comment by heyitslumi** [comment]
very good pull request will recommend

**Pull request closed without merging**
